version: '2'

services:
  mysql:
    image: mysql
    volumes_from:
      - db_data
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  db_data:
    image: mysql
    command: echo "DB data volume!"
    volumes:
      - /var/lib/mysql/

  bridge:
    build: .
    ports:
      - 6060:6060
      - 8001:8001
    command: bash -c "/go/src/app/bin/bridge --migrate-db && /go/src/app/bin/bridge"
    links:
      - mysql
    volumes:
      - ${PWD}/app/:/go/src/app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1