mysql:
  image: mysql
  volumes_from:
    - db_data
  ports:
    - '3306:3306'
  environment:
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_DATABASE: mysql
    MYSQL_ROOT_PASSWORD: mysql

db_data:
  image: mysql
  command: echo "DB data volume!"
  volumes:
    - /var/lib/mysql/

bridge:
  build: .
  ports:
    - 6060:6060
    - 8001:8001
  command: bash -c "/go/src/app/bin/bridge --migrate-db && /go/src/app/bin/bridge"
  links:
    - mysql